#! /bin/bash

set -e

clear
git add .
git commit -m yaccg || true
git push || true
gh workflow run bench1
sleep 35
export wfid=$(gh run list --workflow bench1 |head -n 1 |cut -f 7)
export jid=$(gh run view -v $wfid|grep -o "ID.*)"|grep -o "[[:digit:]]\+")
gh run watch $wfid || true
gh run view --log --job $jid|grep -i player
gh run view --log --job $jid|grep -i valuation|tail -n 1
gh run view --log --job $jid|grep -i variation|tail -n 1


