name: Chess

on:
  workflow_dispatch:

jobs:
  bench:
    name: Bench Job
    runs-on: ubuntu-latest
    timeout-minutes: 355

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Preparations
        run: |
          sudo apt update
          sudo apt install -y git build-essential
          _ICCF=0 _NOEDIT=2 _CHESS960=0 sh build.sh
          chmod 0755 adzchess
      
      - name: Execution
        run: |
          GN=8
          LTG=18000
          PROCESSORS=2
          ulimit -t $LTG
          for n in $(seq 1 $PROCESSORS); do
            fisher=false sh dlpgn.sh $GN >$GN.txt
            ./adzchess go >$GN.2.txt 2>&1 &
            GN=$(($GN + 1))
          done
          wait
          GN=8
          for n in $(seq 1 $PROCESSORS); do
            cat $GN.txt
            cat $GN.2.txt | tail -n 1
            GN=$(($GN + 1))
          done

