name: Bench and Deploy to GitHub Pages

on:
  workflow_dispatch:
  #push:
    #branches: [main]

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  bench:
    name: Bench and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ./baeagn
          key: ${{ runner.os }}-build-${{ hashFiles('build.sh', '**/*.cpp', '**/*.h') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Preparations
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install -y git pgn-extract build-essential
          sh build.sh

      - name: Run bench and capture log
        run: |
          ulimit -t 21300
          mkdir -p _site
          timeout 6h ./baeagn > _site/log.txt 2> _site/error.txt || \
          { echo "Bench failed or timed out"; cat _site/error.txt; exit 1; }

      - name: Copy HTML and assets
        run: |
          cp index.html start.pgn _site/

      - name: Create job summary
        run: |
          echo "## Bench Results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Benchmark completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "Log size: $(wc -l < _site/log.txt) lines" >> $GITHUB_STEP_SUMMARY

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: bench
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
